list1 = [
    'Authentication Bypass', 'Exploitation of insufficient logging and monitoring', 'Attackers gain access to unauthorised data by exploiting vulnerabilities in the service', 'Authentication Bypass', 'Data leakage or disclosure to unauthorized parties', 'Attackers who compromise the application or application server could directly access and modify the data store', 'Sensitive data is exposed through weak security configurations', 'Attackers use known cloud vulnerabilities to access unauthorized data', 'Excessive Allocation', 'Attackers compromise images by modifying their content', 'Attackers gain access to the sensitive data through injecting code in the repositories', 'Availability is compromised through attacks against scalability configuration', 'Sensitive data is compromised by unauthorized access to container volumes', 'Exploitation of insufficient logging and monitoring', 'Sensitive data is compromised through network access', 'Attackers gain unauthorised access to data and/or systems through SQL Injection attacks', 'Attackers gain access to unauthorised data by exploiting vulnerabilities in the service', 'Authentication Bypass', 'Data leakage or disclosure to unauthorized parties', 'Attackers who compromise the application or application server could directly access and modify the data store', 'Sensitive data is exposed through weak security configurations', 'Attackers use known cloud vulnerabilities to access unauthorized data', 'Excessive Allocation', 'Attackers compromise images by modifying their content', 'Attackers gain access to the sensitive data through injecting code in the repositories', 'Availability is compromised through attacks against scalability configuration', 'Sensitive data is compromised by unauthorized access to container volumes', 'Exploitation of insufficient logging and monitoring', 'Sensitive data is compromised through network access', 'Attackers gain unauthorised access to data and/or systems through SQL Injection attacks', 'An adversary embeds malicious scripts in content that will be served to web browsers', 'Application contains security vulnerabilities not identified during the development process', 'Attackers gain unauthorised access to data by compromising third party web resources', 'Attackers gain unauthorised access to data or services by accessing a client side secret', 'Attackers gain unauthorised access to the application by the use of deprecated client-side technologies', 'An adversary embeds malicious scripts in content that will be served to web browsers', 'Attackers could gain access to sensitive data through a man in the middle attack', 'Privilege Abuse', 'Attackers cause users to peform arbitrary clicks on the site through ClickJacking attacks', 'Sensitive data is exposed through weak security configurations', 'Attackers use known cloud vulnerabilities to access unauthorized data', 'Excessive Allocation', 'Attackers compromise images by modifying their content', 'Attackers gain access to the sensitive data through injecting code in the repositories', 'Availability is compromised through attacks against scalability configuration', 'Sensitive data is compromised by unauthorized access to container volumes', 'Exploitation of insufficient logging and monitoring', 'Sensitive data is compromised through network access', 'Attackers gain access to unauthorised data by exploiting vulnerabilities in the service', 'Authentication Bypass', 'Data leakage or disclosure to unauthorized parties', 'Attackers who compromise the application or application server could directly access and modify the data store', 'Sensitive data is exposed through weak security configurations', 'Attackers use known cloud vulnerabilities to access unauthorized data', 'Excessive Allocation', 'Attackers compromise images by modifying their content', 'Attackers gain access to the sensitive data through injecting code in the repositories', 'Availability is compromised through attacks against scalability configuration', 'Sensitive data is compromised by unauthorized access to container volumes', 'Exploitation of insufficient logging and monitoring', 'Sensitive data is compromised through network access', 'Attackers gain unauthorised access to data and/or systems through SQL Injection attacks', 'An attacker could send malicious push notifications, leading to unauthorized actions, data breaches, or phishing attacks', 'Attackers could gain access to sensitive data through a man in the middle attack', 'Attackers gain unauthorised access to data and/or systems through SQL Injection attacks', 'Attackers gain unauthorized access to the control of the environment', 'Attackers gain unauthorized access to the user account due to the lack of configuration of the account', 'Attackers perform a Denial of Service (DoS)', 'Data is intentionally or accidentally deleted', 'An attacker attempts to invoke all common switches and options to discover weaknesses', 'Application contains security vulnerabilities not identified during the development process', "Attacker gains access to sensitive data by modifying the application's expected behavior", 'Users lose trust in the application because it requests unnecessary privileges', 'Accessing Functionality Not Properly Constrained by ACLs', 'Attackers gain access to the data through the WebView functionality', 'Attackers gain unauthorised access to the application through an error handling flaw', 'Attackers gain unauthorised access to the application through buffer overflow flaws', 'An adversary embeds malicious scripts in content that will be served to web browsers', 'Application contains security vulnerabilities not identified during the development process', 'Attackers gain unauthorised access to data by compromising third party web resources', 'Attackers gain unauthorised access to data or services by accessing a client side secret', 'Attackers gain unauthorised access to the application by the use of deprecated client-side technologies', 'An adversary embeds malicious scripts in content that will be served to web browsers', 'Attackers could gain access to sensitive data through a man in the middle attack', 'Privilege Abuse', 'Attackers cause users to peform arbitrary clicks on the site through ClickJacking attacks', 'Attackers gain access to unauthorised data by exploiting vulnerabilities in the service', 'Authentication Bypass', 'Data leakage or disclosure to unauthorized parties', 'Attackers who compromise the application or application server could directly access and modify the data store', 'Sensitive data is exposed through weak security configurations', 'Attackers use known cloud vulnerabilities to access unauthorized data', 'Excessive Allocation', 'Attackers compromise images by modifying their content', 'Attackers gain access to the sensitive data through injecting code in the repositories', 'Availability is compromised through attacks against scalability configuration', 'Sensitive data is compromised by unauthorized access to container volumes', 'Exploitation of insufficient logging and monitoring', 'Sensitive data is compromised through network access', 'Attackers gain unauthorised access to data and/or systems through SQL Injection attacks', 'Attackers gain access to unauthorised data by exploiting vulnerabilities in the service', 'Authentication Bypass', 'Data leakage or disclosure to unauthorized parties', 'Attackers who compromise the application or application server could directly access and modify the data store', 'Sensitive data is exposed through weak security configurations', 'Attackers use known cloud vulnerabilities to access unauthorized data', 'Excessive Allocation', 'Attackers compromise images by modifying their content', 'Attackers gain access to the sensitive data through injecting code in the repositories', 'Availability is compromised through attacks against scalability configuration', 'Sensitive data is compromised by unauthorized access to container volumes', 'Exploitation of insufficient logging and monitoring', 'Sensitive data is compromised through network access', 'An adversary embeds malicious scripts in content that will be served to web browsers', 'Application contains security vulnerabilities not identified during the development process', 'Attackers gain unauthorised access to data or services by accessing a client side secret', 'Attackers gain unauthorised access to the application by the use of deprecated client-side technologies', 'Attackers could gain access to sensitive data through a man in the middle attack'
]

list2 = [
    "Auth Bypass",
    "Insufficient Logging Exploit",
    "Unauthorized Data Access",
    "Auth Bypass",
    "Data Leakage",
    "App Data Manipulation",
    "Weak Security Config",
    "Cloud Vuln. Exploit",
    "Excessive Allocation",
    "Image Tampering",
    "Code Injection",
    "Scalability Attack",
    "Container Access",
    "Insufficient Logging Exploit",
    "Network Data Compromise",
    "SQL Injection",
    "Unauthorized Data Access",
    "Auth Bypass",
    "Data Leakage",
    "App Data Manipulation",
    "Weak Security Config",
    "Cloud Vuln. Exploit",
    "Excessive Allocation",
    "Image Tampering",
    "Code Injection",
    "Scalability Attack",
    "Container Access",
    "Insufficient Logging Exploit",
    "Network Data Compromise",
    "SQL Injection",
    "Script Injection",
    "Undiscovered Security Vulnerabilities",
    "Third-Party Compromise",
    "Client Secret Breach",
    "Deprecated Tech Exploit",
    "Script Injection",
    "MITM Attack",
    "Privilege Abuse",
    "Clickjacking",
    "Weak Security Config",
    "Cloud Vuln. Exploit",
    "Excessive Allocation",
    "Image Tampering",
    "Code Injection",
    "Scalability Attack",
    "Container Access",
    "Insufficient Logging Exploit",
    "Network Data Compromise",
    "Unauthorized Data Access",
    "Auth Bypass",
    "Data Leakage",
    "App Data Manipulation",
    "Weak Security Config",
    "Cloud Vuln. Exploit",
    "Excessive Allocation",
    "Image Tampering",
    "Code Injection",
    "Scalability Attack",
    "Container Access",
    "Insufficient Logging Exploit",
    "Network Data Compromise",
    "SQL Injection",
    "Push Notification Exploit",
    "MITM Attack",
    "SQL Injection",
    "Unauthorized Environment Control",
    "Account Config Weakness",
    "Denial of Service",
    "Data Deletion",
    "Fuzzing Attack",
    "Undiscovered Security Vulnerabilities",
    "Behavior Mod. Exploit",
    "Unnecessary Privilege Req.",
    "ACL Bypass",
    "WebView Exploit",
    "Error Handling Flaw",
    "Buffer Overflow Attack",
    "Script Injection",
    "Undiscovered Security Vulnerabilities",
    "Third-Party Compromise",
    "Client Secret Breach",
    "Script Injection",
    "MITM Attack",
    "Privilege Abuse",
    "Clickjacking",
    "Unauthorized Data Access",
    "Auth Bypass",
    "Data Leakage",
    "App Data Manipulation",
    "Weak Security Config",
    "Cloud Vuln. Exploit",
    "Excessive Allocation",
    "Image Tampering",
    "Code Injection",
    "Scalability Attack",
    "Container Access",
    "Insufficient Logging Exploit",
    "Network Data Compromise",
    "SQL Injection",
    "Unauthorized Data Access",
    "Auth Bypass",
    "Data Leakage",
    "App Data Manipulation",
    "Weak Security Config",
    "Cloud Vuln. Exploit",
    "Excessive Allocation",
    "Image Tampering",
    "Code Injection",
    "Scalability Attack",
    "Container Access",
    "Insufficient Logging Exploit",
    "Network Data Compromise",
    "SQL Injection",
    "Weak Security Config",
    "Cloud Vuln. Exploit",
    "Excessive Allocation",
    "Image Tampering",
    "Code Injection",
    "Scalability Attack",
    "Container Access",
    "Insufficient Logging Exploit",
    "Network Data Compromise",
    "Script Injection",
    "Undiscovered Security Vulnerabilities",
    "Client Secret Breach",
    "Deprecated Tech Exploit",
    "MITM Attack"
]

# Define a mapping between phrases in list1 and their corresponding abbreviations in list2
mapping = {
    'Authentication Bypass': 'Auth Bypass',
    'Exploitation of insufficient logging and monitoring': 'Insufficient Logging Exploit',
    'Attackers gain access to unauthorised data by exploiting vulnerabilities in the service': 'Unauthorized Data Access',
    'Data leakage or disclosure to unauthorized parties': 'Data Leakage',
    'Attackers who compromise the application or application server could directly access and modify the data store': 'App Data Manipulation',
    'Sensitive data is exposed through weak security configurations': 'Weak Security Config',
    'Attackers use known cloud vulnerabilities to access unauthorized data': 'Cloud Vuln. Exploit',
    'Excessive Allocation': 'Excessive Allocation',
    'Attackers compromise images by modifying their content': 'Image Tampering',
    'Attackers gain access to the sensitive data through injecting code in the repositories': 'Code Injection',
    'Availability is compromised through attacks against scalability configuration': 'Scalability Attack',
    'Sensitive data is compromised by unauthorized access to container volumes': 'Container Access',
    'Sensitive data is compromised through network access': 'Network Data Compromise',
    'Attackers gain unauthorised access to data and/or systems through SQL Injection attacks': 'SQL Injection',
    'An adversary embeds malicious scripts in content that will be served to web browsers': 'Script Injection',
    'Application contains security vulnerabilities not identified during the development process': 'Undiscovered Security Vulnerabilities',
    'Attackers gain unauthorised access to data by compromising third party web resources': 'Third-Party Compromise',
    'Attackers gain unauthorised access to data or services by accessing a client side secret': 'Client Secret Breach',
    'Attackers gain unauthorised access to the application by the use of deprecated client-side technologies': 'Deprecated Tech Exploit',
    'Attackers could gain access to sensitive data through a man in the middle attack': 'MITM Attack',
    'Privilege Abuse': 'Privilege Abuse',
    'Attackers cause users to peform arbitrary clicks on the site through ClickJacking attacks': 'Clickjacking',
    'An attacker could send malicious push notifications, leading to unauthorized actions, data breaches, or phishing attacks': 'Push Notification Exploit',
    'Attackers gain unauthorized access to the control of the environment': 'Unauthorized Environment Control',
    'Attackers gain unauthorized access to the user account due to the lack of configuration of the account': 'Account Config Weakness',
    'Attackers perform a Denial of Service (DoS)': 'Denial of Service',
    'Data is intentionally or accidentally deleted': 'Data Deletion',
    'An attacker attempts to invoke all common switches and options to discover weaknesses': 'Fuzzing Attack',
    "Attacker gains access to sensitive data by modifying the application's expected behavior": 'Behavior Mod. Exploit',
    'Users lose trust in the application because it requests unnecessary privileges': 'Unnecessary Privilege Req.',
    'Accessing Functionality Not Properly Constrained by ACLs': 'ACL Bypass',
    'Attackers gain access to the data through the WebView functionality': 'WebView Exploit',
    'Attackers gain unauthorised access to the application through an error handling flaw': 'Error Handling Flaw',
    'Attackers gain unauthorised access to the application through buffer overflow flaws': 'Buffer Overflow Attack'
}


# Convert list1 items to their corresponding mapped items from list2
mapped_list1 = [mapping.get(item, item) for item in list1]

# Find items in list1 that do not have a corresponding mapping in list2
unmapped_items = [item for item in mapped_list1 if item not in list2]

print(len(list1),list1[0])
print(len(list2),list2[0])
print(unmapped_items)

